- .rubocop.yml
- Gemfile
- Gemfile.lock
- db/seeds/04_proposal_fields.rb
- lib/tasks/subject.rake
- spec/factories/people.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Run Rubocop from the 'proposals' directory with `bundle exec rubocop`
> Rubocup setup [Finishes #177675168]

- .circleci/config-build-image.yml
- .circleci/config-in-container.yml
- .circleci/config.yml
- Gemfile
PR should trigger CircleCI build
> Merge Development update

- app/controllers/submit_proposals_controller.rb
- app/helpers/proposals_helper.rb
- app/services/submit_proposal_service.rb
- app/views/proposals/_proposal.html.erb
- spec/helpers/proposals_helper_spec.rb
https://trello.com/c/B3Hf5siQ/45-saving-a-draft-crashes-app
https://trello.com/c/NeqqsKMu/25-title-subject-validations-not-working
https://trello.com/c/Crtf1CEW/17-after-completing-all-the-steps-when-i-click-submit-for-review
> Fix validation

- app/controllers/invites_controller.rb
- app/mailers/invite_mailer.rb
- app/models/proposal.rb
- app/views/invite_mailer/invite_acceptance.html.erb
- app/views/invite_mailer/invite_acceptance.text.erb
- app/views/invite_mailer/invite_email.html.erb
- app/views/invite_mailer/invite_email.text.erb
https://trello.com/c/zy0VixlZ/34-update-notification-email-templates
> Reword notification emails templates

- app/views/proposal_fields/_date.html.erb
- app/views/proposal_fields/_multi_choice.html.erb
- app/views/proposal_fields/_preferred_impossible_date.html.erb
- app/views/proposal_fields/_radio.html.erb
- app/views/proposal_fields/_single_choice.html.erb
- app/views/proposal_fields/_text.html.erb
https://trello.com/c/kBF1ynhJ/6-learn-more-links
> learn more links

- app/javascript/controllers/proposal_form_controller.js
- app/views/proposal_fields/_preferred_impossible_date.html.erb
- app/views/proposal_fields/_text.html.erb
- app/views/proposals/_proposal.html.erb
https://trello.com/c/xMmgG42s/47-fix-question-edit
> Fix edit text field

- app/controllers/survey_controller.rb
- app/controllers/users/sessions_controller.rb
- app/models/person.rb
https://trello.com/c/nbhHtFNz/29-collect-organizers-demographic-data
> Collect demographic data

- app/controllers/submit_proposals_controller.rb
- app/views/invites/new.html.erb
- app/views/proposal_types/_form.html.erb
- app/views/proposals/_proposal.html.erb
https://trello.com/c/KXm5KAAa/52-when-saving-a-draft-skip-validations-and-add-flash-message-draft-saved
https://trello.com/c/v3bQVVmQ/48-rename-co-organizers-to-co-organizers-or-supporting-organizers
https://trello.com/c/9xiYRB7O/51-the-type-of-meeting-field-on-the-proposal-submiss[…]m-should-not-downcase-the-proposal-type-in-the-uneditable-field
> UI changes

- app/assets/stylesheets/proposal_forms.css
- app/views/pages/_edi_rubric.html.erb
- app/views/pages/_scientific_merit_rubric.html.erb
- app/views/pages/guidelines.html.erb
https://trello.com/c/tJVlDyd3/9-formatting-edits-needed-for-proposal-guidelines
> formatting for proposal guidelines

- app/controllers/invites_controller.rb
- app/controllers/proposals_controller.rb
- app/helpers/invites_helper.rb
- app/javascript/controllers/submit_proposals_controller.js
- app/views/proposals/_invite.html.erb
- app/views/proposals/_proposal.html.erb
https://trello.com/c/XDRXpNFb/31-reorganize-co-organizer-and-participant-invitation-feature-so-they-appear-on-step-1-under-subject-areas
> Reorganize invitation feature

- app/controllers/proposal_types_controller.rb
- app/controllers/submit_proposals_controller.rb
- app/helpers/proposal_fields_helper.rb
- app/javascript/controllers/submit_proposals_controller.js
- app/views/proposal_fields/_date.html.erb
- app/views/proposal_fields/_multi_choice.html.erb
- app/views/proposal_fields/_preferred_impossible_date.html.erb
- app/views/proposal_fields/_radio.html.erb
- app/views/proposal_fields/_single_choice.html.erb
- app/views/proposal_fields/_text.html.erb
- app/views/proposals/_proposal.html.erb
- spec/helpers/proposal_fields_helper_spec.rb
https://trello.com/c/OWQq3lH8/72-change-location-selection-back-to-multi-select
https://trello.com/c/KXm5KAAa/52-when-saving-a-draft-skip-validations-and-add-flash-message-draft-saved
> Proposal save as draft

- app/controllers/invites_controller.rb
- app/helpers/proposals_helper.rb
- app/javascript/controllers/proposal_form_controller.js
- app/javascript/controllers/submit_proposals_controller.js
- app/models/invite.rb
- app/models/proposal.rb
- app/views/proposals/_invite.html.erb
- app/views/proposals/_proposal.html.erb
- app/views/proposals/index.html.erb
- app/views/submit_proposals/thanks.html.erb
- spec/factories/invites.rb
- spec/requests/invites_spec.rb
* added intro text to Add Organizers
* renamed invite.status from "completed" to "confirmed"
* added validation for minimum number of organizers
> Disable Add Participants if Organizer is being entered

- app/controllers/users/sessions_controller.rb
https://trello.com/c/OnEasdCr/95-the-survey-new-view-with-the-introduction-and-disclaimer-is-not-displayed-for-new-users-upon-confirmation-first-login
> Redirect to new survey page

- app/views/proposals/_organizer.html.erb
- app/views/proposals/_proposal.html.erb
https://trello.com/c/QHH2nlap/84-bug-when-i-view-the-submitted-proposal-i-dont-get[…]-of-co-organizers-who-confirmed-nor-the-participant-list-that-i
> Show participants list on proposal show

- app/views/proposals/_lead_organizer.html.erb
- app/views/proposals/_proposal.html.erb
https://trello.com/c/JBBWuiuN/111-add-heading-lead-organizer-with-their-name-above-add-supporting-organizer
> showing lead organizer

- spec/factories/people.rb
- spec/requests/proposals_spec.rb
- spec/support/authentication.rb
missing `latex_out` code because of getting proposal_id nill from session. 
how to deal with session in rspec.
> Add tests for proposals controller

- app/views/proposals/_proposal.html.erb
Reverts birs-math/proposals#239
> Revert "Fix link for print proposal"

- app/helpers/people_helper.rb
- app/models/person.rb
- app/views/devise/sessions/new.html.erb
- app/views/people/new.html.erb
- config/locales/devise.en.yml
- public/500.html
Reverts birs-math/proposals#250
> Revert "Updated error messages"

- app/services/edit_flow_service.rb
This schema is now live on the demo endpoint.
> Update EF submission mutation to use new GraphQL submission schema

- app/controllers/proposals_controller.rb
- app/views/invite_mailer/invite_acceptance.html.erb
- app/views/invite_mailer/invite_acceptance.text.erb
- app/views/invite_mailer/invite_email.html.erb
- app/views/invite_mailer/invite_email.text.erb
- app/views/invite_mailer/invite_reminder.html.erb
- app/views/invite_mailer/invite_reminder.text.erb
- app/views/proposals/_email_preview.html.erb
* Added deadline to the invitation emails
* Started update of email preview, but missing @invitation data -- perhaps a POST could be sent to the controller when the Invite Organizer button is pressed, to send the form information to the controller so it can be displayed in the modal?
> Deadline added to invitation emails, preview update started

- .rubocop.yml
- app/controllers/users/registrations_controller.rb
* also - don't overwrite existing Person record's name with sign-up form input
> downcase email before search

- app/helpers/people_helper.rb
- app/helpers/survey_helper.rb
* What other countries are missing?
* Why only some countries in the survey citizenship list?
> added Austria

- app/controllers/application_controller.rb
- app/controllers/proposals_controller.rb
- app/controllers/submit_proposals_controller.rb
- app/controllers/users/sessions_controller.rb
- app/models/proposal.rb
- app/views/proposals/_proposal_list.html.erb
- app/views/proposals/index.html.erb
- app/views/proposals/new.html.erb
* post-login path to proposal#new unless is organizer with proposals
* only add proposal to proposals index if user is an organizer of them
* validation messages on draft save bugfix
* helpful headings
> UX improvements

- app/javascript/channels/import_channel.js
- app/javascript/channels/proposal_booklet_channel.js
- app/javascript/channels/review_channel.js
- app/views/layouts/application.html.erb
Websockets fails to connect at all.
Reverts birs-math/proposals#714
> Revert "Added condition for channels streaming"

- app/controllers/schedules_controller.rb
- app/models/location.rb
- app/services/hungarian_monte_carlo.rb
- app/views/layouts/_sidebar.html.erb
- app/views/schedules/form.html.erb
- db/migrate/20211201040031_add_test_mode_to_schedule_runs.rb
- db/schema.rb
> add test_mode to ScheduleRuns, HMC improvements

- app/javascript/controllers/nested_invites_controller.js
Reverts birs-math/proposals#866
> Revert "Issue Fixed/ staging deployement"

- app/services/edit_flow_service.rb
- spec/models/person_spec.rb
- spec/services/edit_flow_service_spec.rb
- spec/support/factory_helpers.rb
Reverts birs-math/proposals#904
> Revert "updated deprecated countries gem method for name"

- .gitignore
- Gemfile
- Gemfile.lock
- config/application.rb
Reverts birs-math/proposals#909
> Revert "Added dotenv gem for getting env variables to staging"

- app/controllers/submitted_proposals_controller.rb
- app/helpers/proposals_helper.rb
- app/services/edit_flow_service.rb
- spec/models/person_spec.rb
- spec/services/edit_flow_service_spec.rb
- spec/support/factory_helpers.rb
> Updated deprecated method for country name causing editflow issue

- Gemfile
- Gemfile.lock
- app/controllers/submitted_proposals_controller.rb
- app/models/proposal.rb
- app/services/import_reviews_service.rb
- config/routes.rb
- spec/factories/proposals.rb
- spec/models/proposal_type_spec.rb
- spec/requests/people_spec.rb
- spec/requests/submitted_proposals_spec.rb
- spec/services/booklet_pdf_service_spec.rb
- spec/spec_helper.rb
This PR fixes some issues with failing tests, removes failing duplicated tests and other unneeded stuff, and in the end, makes sure that CI is green. It is just a bare minimum, test suit requires a complete overhaul as tests basically test nothing.
> Bare minimum to fix test suit

- app/views/invites/show.html.erb
This PR just updates a text on rsvp page
> Update rsvp page text

- config/cable.yml
- config/contacts.yml
- config/database.yml
- config/environments/staging.rb
- config/secrets.yml
- config/webpacker.yml
This PR adds a staging environment to proposals app, the main need is to allow development and staging to have separate cable.yml configs.
> Add a proper staging environment

- app/views/proposals/_proposal.html.erb
- app/views/submitted_proposals/_form.html.erb
This PR removes duplicate `Confirmed Participants` block.
> Remove duplicated confirmed members block

- app/controllers/invites_controller.rb
- app/controllers/proposals_controller.rb
- app/controllers/submitted_proposals_controller.rb
- app/models/proposal.rb
- spec/requests/invites_spec.rb
This PR makes so that views try to use proposal code in URL and then default to id if code is not present
> Proposals find by code

- app/views/proposals/_proposal.html.erb
- app/views/proposals/form/_fields.html.erb
- app/views/proposals/proposal_version.html.erb
- app/views/submitted_proposals/_form.html.erb
This PR adds a commit that was not merged during https://github.com/birs-math/proposals/pull/982 due to poor rebase
> Fix proposal latex form

- config/locales/en.yml
- spec/features/proposal_edit_spec.rb
Just a small text update on a button
> Update button text for inviting participants

- app/controllers/submitted_proposals_controller.rb
- app/services/proposal_pdf_service.rb
This PR fixes recent production errors
> Hot fix recent production errors

- app/controllers/submit_proposals_controller.rb
- app/services/proposal_field_validations_service.rb
- spec/requests/submit_proposals_spec.rb
This is a quick PR that will let staff submit proposals as well as change staff redirect URL to be the same edit submitted proposal page
> Allow staff to submit proposals

- app/controllers/submitted_proposals_controller.rb
- app/helpers/proposals_helper.rb
- app/helpers/submitted_proposals_helper.rb
- app/javascript/controllers/submitted_proposals_controller.js
- app/javascript/js/common.js
- app/models/person.rb
- app/models/proposal.rb
- app/models/proposal_role.rb
- app/models/role.rb
- app/views/submitted_proposals/_email_templates.html.erb
- app/views/submitted_proposals/_outcome_location_window.html.erb
- app/views/submitted_proposals/_review_booklet_window.html.erb
- app/views/submitted_proposals/index.html.erb
- app/views/submitted_proposals/index.turbo_stream.erb
- app/views/submitted_proposals/index/_proposal_row_placeholder.html.erb
- app/views/submitted_proposals/index/_proposals_by_type.html.erb
This PR moves action bar on the bottom to each proposal type block, those buttons only interact with proposals from the same proposal type block.
> Action bar for each proposal type

- app/controllers/submitted_proposals_controller.rb
- app/models/proposal.rb
This PR is a fix to recent preload errors in /submitted_proposals page
> Fix preloading errors

- app/helpers/survey_helper.rb
This is just a text update for survey option. It would be good to refactor survey options some time in the future
> Update survey option text for Native American

- .circleci/config.yml
- db/schema.rb
- entrypoint.sh
- spec/requests/submit_proposals_spec.rb
Pin bundler and be careful about invoking rake
> Pin bundler
